const destinationsData = [
  {
    country: "Afghanistan",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "AeroMobile® enabled Int'l Airlines",
    sudp: false,
    idp: true,
    ppu: false,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Aland Islands",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Albania",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Algeria",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "American Samoa",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Andorra",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Angola",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Anguilla",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Antarctica",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G"],
    slowDown: false,
  },
  {
    country: "Antigua & Barbuda",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Argentina",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Armenia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Aruba",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Ascension Island",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G"],
    slowDown: false,
  },
  {
    country: "Australia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Austria",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Azerbaijan",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Azores",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Bahamas",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Bahrain",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Bangladesh",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Barbados",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Belarus",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Belgium",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Belize",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Benin",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Bermuda",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Bhutan",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Bolivia",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Bonaire, St. Eustatius & Saba",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Bosnia & Herzegovina",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Botswana",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Brazil",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "British Virgin Islands",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Brunei",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Bulgaria",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Burkina Faso",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Burundi",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Cambodia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Cameroon",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Canada",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Cape Verde",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Cayman Islands",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Central African Republic",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Chad",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Chile",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "China",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Christmas Island",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Colombia",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Comoros",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G"],
    slowDown: false,
  },
  {
    country: "Congo (Republic of the Congo)",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Cook Islands",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Costa Rica",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Cote D'Ivoire",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Croatia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Cruise Ships",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Cuba - Pay Per Use Only",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: true,
  },
  {
    country: "Curacao",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Cyprus",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Czech Republic",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Democratic Republic of the Congo (DR Congo)",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Denmark",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Djibouti",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Dominica",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Dominican Republic",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "East Timor",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Easter Island",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Ecuador",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Egypt",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "El Salvador",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "England (UK)",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Equatorial Guinea",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Estonia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Eswatini",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Ethiopia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Falkland Islands",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G"],
    slowDown: false,
  },
  {
    country: "Faroe Islands",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Fiji",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Finland",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "France",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "French Guiana",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "French Polynesia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "French West Indies",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Gabon",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Galapagos Islands",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Gambia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Georgia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Germany",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Ghana ",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Gibraltar",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Great Britain (UK)",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Greece",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Greenland",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Grenada",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Guadeloupe",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Guam",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Guatemala",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Guernsey",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Guinea",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Guinea-Bissau",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Guyana",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Haiti",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Holy See",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Honduras",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Hong Kong",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Hungary",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Iceland",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "India",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Indonesia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Iraq",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Ireland",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Isle of Man",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Israel",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Italy",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Ivory Coast",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Jamaica",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Japan",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Jersey",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Jordan",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Kazakhstan",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Kenya",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Kiribati",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["3G"],
    slowDown: false,
  },
  {
    country: "Korea (South Korea)",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Kosovo",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Kuwait",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Kyrgyzstan",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Laos",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Latvia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Lebanon",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G"],
    slowDown: false,
  },
  {
    country: "Lesotho",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Liberia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Libya",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G"],
    slowDown: false,
  },
  {
    country: "Liechtenstein",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Lithuania",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Luxembourg",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Macao (Macau)",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },

  {
    country: "Macedonia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Madagascar",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Madeira",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Malawi",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Malaysia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Maldives",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Mali",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Malta",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Martinique",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Mauritania",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Mauritius",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Mayotte",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Mexico",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: true,
  },
  {
    country: "Micronesia, Federated States Of",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G"],
    slowDown: false,
  },
  {
    country: "Moldova",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Monaco",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Mongolia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Montenegro",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Montserrat",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Morocco",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Mozambique",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Myanmar",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Namibia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Nauru",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Nepal",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Netherlands",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Netherlands Antilles",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "New Caledonia",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "New Zealand",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Nicaragua",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Niger",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Nigeria",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Norfolk Island",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G"],
    slowDown: false,
  },
  {
    country: "Northern Ireland (UK)",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Northern Mariana Islands",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Norway",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Oman",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Pakistan",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Palau",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Palestinian Authority",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Panama",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Papua New Guinea",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Paraguay",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Peru",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Philippines",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Poland",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Portugal",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Qatar",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Reunion Island",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Romania",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Russia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Rwanda",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Saipan",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Samoa",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "San Marino",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Sao Tome & Principe",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Saudi Arabia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Scotland (UK)",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Senegal",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Serbia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Seychelles",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Sierra Leone",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Singapore",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Slovakia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Slovenia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Solomon Islands",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Somalia",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G"],
    slowDown: false,
  },
  {
    country: "South Africa",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "South Korea",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "South Sudan",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Spain",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Sri Lanka",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "St. Barthelemy",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "St. Eustatius & Saba",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "St. Helena",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G"],
    slowDown: false,
  },
  {
    country: "St. Kitts & Nevis",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "St. Lucia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "St. Maarten (Sint Maarten)",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "St. Martin",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "St. Pierre & Miquelon",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G"],
    slowDown: false,
  },
  {
    country: "St. Vincent & the Grenadines",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Sudan",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Suriname",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Svalbard",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Swaziland",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Sweden",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Switzerland",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Syria",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G"],
    slowDown: false,
  },
  {
    country: "Tahiti",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Taiwan",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Tajikistan",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Tanzania",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Thailand",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Timor Leste",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Togo",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Tonga",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Trinidad & Tobago",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Tunisia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Turkey",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Turkmenistan",
    sudp: false,
    idp: false,
    ppu: true,
    services: {
      data: false,
      calling: true,
      text: true,
      mms: false,
      hdv: false,
    },
    technology: ["2G"],
    slowDown: false,
  },
  {
    country: "Turks & Caicos",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Uganda",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Ukraine",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "United Arab Emirates",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "United Kingdom",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Uruguay",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Uzbekistan",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Vanuatu",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Vatican City",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Venezuela",
    sudp: true,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G"],
    slowDown: false,
  },
  {
    country: "Vietnam",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Virgin Islands (British Virgin Islands",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Wales (UK)",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: true,
    },
    technology: ["2G", "3G", "4G", "5G"],
    slowDown: false,
  },
  {
    country: "Western Sahara",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Yemen",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G"],
    slowDown: false,
  },
  {
    country: "Zambia",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
  {
    country: "Zimbabwe",
    sudp: false,
    idp: true,
    ppu: true,
    services: {
      data: true,
      calling: true,
      text: true,
      mms: true,
      hdv: false,
    },
    technology: ["2G", "3G", "4G"],
    slowDown: false,
  },
];

export default destinationsData;
